"""add image prop to Spot module

Revision ID: 4201b0fe7b0e
Revises: e009aa39fef5
Create Date: 2024-07-26 14:45:47.792026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4201b0fe7b0e'
down_revision = 'e009aa39fef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
