"""add created_at and updated_at Spot Model

Revision ID: c4792376e0e9
Revises: c574eb5aa42f
Create Date: 2024-07-29 14:45:38.248809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4792376e0e9'
down_revision = 'c574eb5aa42f'
branch_labels = None
depends_on = None


def upgrade():

    op.add_column('spots', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('spots', sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
