"""add spot seed

Revision ID: e009aa39fef5
Revises: 4f62e0f43c1f
Create Date: 2024-07-24 13:15:09.434161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e009aa39fef5'
down_revision = '4f62e0f43c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
